import sqlalchemy

from sqlalchemy import MetaData
from sqlalchemy import Column, Integer, String, ForeignKey, Table
from sqlalchemy.orm import relationship, backref
from sqlalchemy.ext.declarative import declarative_base



Base = declarative_base(metadata=MetaData(schema='raw'))


class FireIncidents(Base):
    __tablename__ = 'fire_incidents'

    IncidentNumber = Column("Incident Number", String, nullable=True)
    ExposureNumber = Column("Exposure Number", String, nullable=True)
    Address = Column("Address", String, nullable=True)
    IncidentDate = Column("Incident Date", String, nullable=True)
    CallNumber = Column("Call Number", String, nullable=True)
    AlarmDtTm = Column("Alarm DtTm", String, nullable=True)
    ArrivalDtTm = Column("Arrival DtTm", String, nullable=True)
    CloseDtTm = Column("Close DtTm", String, nullable=True)
    City = Column("City", String, nullable=True)
    zipcode = Column("Zipcode", String, nullable=True)
    Battalion = Column("Battalion", String, nullable=True)
    StationArea = Column("Station Area", String, nullable=True)
    Box = Column("Box", String, nullable=True)
    SuppressionUnits = Column("Suppression Units", String, nullable=True)
    SuppressionPersonnel = Column("Suppression Personnel", String, nullable=True)
    EMSUnits = Column("EMS Units", String, nullable=True)
    EMSPersonnel = Column("EMS Personnel", String, nullable=True)
    OtherUnits = Column("Other Units", String, nullable=True)
    OtherPersonnel = Column("Other Personnel", String, nullable=True)
    FirstUnitOnScene = Column("First Unit On Scene", String, nullable=True)
    EstimatedPropertyLoss = Column("Estimated Property Loss", String, nullable=True)
    EstimatedContentsLoss = Column("Estimated Contents Loss", String, nullable=True)
    FireFatalities = Column("Fire Fatalities", String, nullable=True)
    FireInjuries = Column("Fire Injuries", String, nullable=True)
    CivilianFatalities = Column("Civilian Fatalities", String, nullable=True)
    CivilianInjuries = Column("Civilian Injuries", String, nullable=True)
    NumberofAlarms = Column("Number of Alarms", String, nullable=True)
    PrimarySituation = Column("Primary Situation", String, nullable=True)
    MutualAid = Column("Mutual Aid", String, nullable=True)
    ActionTakenPrimary = Column("Action Taken Primary", String, nullable=True)
    ActionTakenSecondary = Column("Action Taken Secondary", String, nullable=True)
    ActionTakenOther = Column("Action Taken Other", String, nullable=True)
    DetectorAlertedOccupants = Column("Detector Alerted Occupants", String, nullable=True)
    PropertyUse = Column("Property Use", String, nullable=True)
    AreaofFireOrigin = Column("Area of Fire Origin", String, nullable=True)
    IgnitionCause = Column("Ignition Cause", String, nullable=True)
    IgnitionFactorPrimary = Column("Ignition Factor Primary", String, nullable=True)
    IgnitionFactorSecondary = Column("Ignition Factor Secondary", String, nullable=True)
    HeatSource = Column("Heat Source", String, nullable=True)
    ItemFirstIgnited = Column("Item First Ignited", String, nullable=True)
    HumanFactorsAssociatedwithIgnition = Column("Human Factors Associated with Ignition", String, nullable=True)
    StructureType = Column("Structure Type", String, nullable=True)
    StructureStatus = Column("Structure Status", String, nullable=True)
    FloorofFireOrigin = Column("Floor of Fire Origin", String, nullable=True)
    FireSpread = Column("Fire Spread", String, nullable=True)
    NoFlameSpead = Column("No Flame Spead", String, nullable=True)
    Numberoffloorswithminimumdamage = Column("Number of floors with minimum damage", String, nullable=True)
    Numberoffloorswithsignificantdamage = Column("Number of floors with significant damage", String, nullable=True)
    Numberoffloorswithheavydamage = Column("Number of floors with heavy damage", String, nullable=True)
    Numberoffloorswithextremedamage = Column("Number of floors with extreme damage", String, nullable=True)
    DetectorsPresent = Column("Detectors Present", String, nullable=True)
    DetectorType = Column("Detector Type", String, nullable=True)
    DetectorOperation = Column("Detector Operation", String, nullable=True)
    DetectorEffectiveness = Column("Detector Effectiveness", String, nullable=True)
    DetectorFailureReason = Column("Detector Failure Reason", String, nullable=True)
    AutomaticExtinguishingSystemPresent = Column("Automatic Extinguishing System Present", String, nullable=True)
    AutomaticExtinguishingSytemType = Column("Automatic Extinguishing Sytem Type", String, nullable=True)
    AutomaticExtinguishingSytemPerfomance = Column("Automatic Extinguishing Sytem Perfomance", String, nullable=True)
    AutomaticExtinguishingSytemFailureReason = Column("Automatic Extinguishing Sytem Failure Reason", String, nullable=True)
    NumberofSprinklerHeadsOperating = Column("Number of Sprinkler Heads Operating", String, nullable=True)
    point = Column("Location", String, nullable=True)
    SupervisorDistrict = Column("Supervisor District", String, nullable=True)
    neighborhood_district = Column("Neighborhood District", String, nullable=True)
    ID = Column("ID", String, nullable=False, primary_key=True)
    IngestionDate = Column("Ingestion Date", String, nullable=False)



class FireIncidentsV2(Base):
    __tablename__ = 'fire_incident'

    IncidentNumber = Column("Incident Number", String, nullable=True)
    ExposureNumber = Column("Exposure Number", String, nullable=True)
    Address = Column("Address", String, nullable=True)
    IncidentDate = Column("Incident Date", String, nullable=True)
    CallNumber = Column("Call Number", String, nullable=True)
    AlarmDttm = Column("Alarm DtTm", String, nullable=True)
    ArrivalDttm = Column("Arrival DtTm", String, nullable=True)
    CloseDttm = Column("Close DtTm", String, nullable=True)
    City = Column("City", String, nullable=True)
    Zipcode = Column("Zipcode", String, nullable=True)
    Battalion = Column("Battalion", String, nullable=True)
    StationArea = Column("Station Area", String, nullable=True)
    Box = Column("Box", String, nullable=True)
    SuppressionUnits = Column("Suppression Units", String, nullable=True)
    SuppressionPersonnel = Column("Suppression Personnel", String, nullable=True)
    EmsUnits = Column("EMS Units", String, nullable=True)
    EmsPersonnel = Column("EMS Personnel", String, nullable=True)
    OtherUnits = Column("Other Units", String, nullable=True)
    OtherPersonnel = Column("Other Personnel", String, nullable=True)
    FirstUnitOnScene = Column("First Unit On Scene", String, nullable=True)
    EstimatedPropertyLoss = Column("Estimated Property Loss", String, nullable=True)
    EstimatedContentsLoss = Column("Estimated Contents Loss", String, nullable=True)
    FireFatalities = Column("Fire Fatalities", String, nullable=True)
    FireInjuries = Column("Fire Injuries", String, nullable=True)
    CivilianFatalities = Column("Civilian Fatalities", String, nullable=True)
    CivilianInjuries = Column("Civilian Injuries", String, nullable=True)
    NumberOfAlarms = Column("Number of Alarms", String, nullable=True)
    PrimarySituation = Column("Primary Situation", String, nullable=True)
    MutualAid = Column("Mutual Aid", String, nullable=True)
    ActionTakenPrimary = Column("Action Taken Primary", String, nullable=True)
    ActionTakenSecondary = Column("Action Taken Secondary", String, nullable=True)
    ActionTakenOther = Column("Action Taken Other", String, nullable=True)
    DetectorAlertedOccupants = Column("Detector Alerted Occupants", String, nullable=True)
    PropertyUse = Column("Property Use", String, nullable=True)
    AreaOfFireOrigin = Column("Area of Fire Origin", String, nullable=True)
    IgnitionCause = Column("Ignition Cause", String, nullable=True)
    IgnitionFactorPrimary = Column("Ignition Factor Primary", String, nullable=True)
    IgnitionFactorSecondary = Column("Ignition Factor Secondary", String, nullable=True)
    HeatSource = Column("Heat Source", String, nullable=True)
    ItemFirstIgnited = Column("Item First Ignited", String, nullable=True)
    HumanFactorsAssociatedWithIgnition = Column("Human Factors Associated with Ignition", String, nullable=True)
    StructureType = Column("Structure Type", String, nullable=True)
    StructureStatus = Column("Structure Status", String, nullable=True)
    FloorOfFireOrigin = Column("Floor of Fire Origin", String, nullable=True)
    FireSpread = Column("Fire Spread", String, nullable=True)
    NoFlameSpead = Column("No Flame Spead", String, nullable=True)
    Numberoffloorswithminimumdamage = Column("Number of floors with minimum damage", String, nullable=True)
    Numberoffloorswithsignificantdamage = Column("Number of floors with significant damage", String, nullable=True)
    Numberoffloorswithheavydamage = Column("Number of floors with heavy damage", String, nullable=True)
    Numberoffloorswithextremedamage = Column("Number of floors with extreme damage", String, nullable=True)
    DetectorsPresent = Column("Detectors Present", String, nullable=True)
    DetectorType = Column("Detector Type", String, nullable=True)
    DetectorOperation = Column("Detector Operation", String, nullable=True)
    DetectorEffectiveness = Column("Detector Effectiveness", String, nullable=True)
    DetectorFailureReason = Column("Detector Failure Reason", String, nullable=True)
    AutomaticExtinguishingSystemPresent = Column("Automatic Extinguishing System Present", String, nullable=True)
    AutomaticExtinguishingSytemType = Column("Automatic Extinguishing Sytem Type", String, nullable=True)
    AutomaticExtinguishingSytemPerfomance = Column("Automatic Extinguishing Sytem Perfomance", String, nullable=True)
    AutomaticExtinguishingSytemFailureReason = Column("Automatic Extinguishing Sytem Failure Reason", String, nullable=True)
    NumberofSprinklerHeadsOperating = Column("Number of Sprinkler Heads Operating", String, nullable=True)
    Point = Column("Location", String, nullable=True)
    SupervisorDistrict = Column("Supervisor District", String, nullable=True)
    NeighborhoodDistrict = Column("Neighborhood District", String, nullable=True)
    Id = Column("ID", String, nullable=False, primary_key=True)
    IngestionDate = Column("Ingestion Date", String, nullable=False)