version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/appuser/code
    ports:
      - "8000:8000"